language: node_js

node_js:
  - node

cache:
  directories:
    - node_modules

before_install:
  - npm update

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c 'create database politico_db;' -U postgres
  - psql -c "create user politico with PASSWORD 'sheja';" -U postgres

script:
  - npm test
  - npm run coveralls
