language: node_js

node_js:
  - node

script: echo "CI is running......"

cache:
  directories:
  - node_modules

before_install:
- npm update

install:
- npm install


services:
- postgresql

script:
- npm test
- npm run coveralls

